version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crud-productos-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xuglb9q5mcv8"
s3_prefix = "crud-productos-sam"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
