AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Resources:
  SaveHelloFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: handler.saveHello
      Runtime: nodejs18.x
      CodeUri: ./hello
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GreetingTable
      Environment:
        Variables:
          GREETINGS_TABLE: !Ref GreetingTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: POST
  GetHelloFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: handler.getHello
      Runtime: nodejs18.x
      CodeUri: ./hello
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GreetingTable
      Environment:
        Variables:
          GREETINGS_TABLE: !Ref GreetingTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: GET

  GreetingTable:
    Type: AWS::Serverless::SimpleTable

#Outputs:
#  MyApi:
#   Description: "URL"
#   V
